### ISSUE TITLE
minor fix to interactions figure

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/ForestGEO-tree-rings#134]
@ValentineHerr , I just noticed that for the interactions figure in the appendix, we have "no significant main effect" where we'd want "no significant interactions". Could you please fix this? (I'm trying to submit this AM and won't let this slow me down. If you can fix it before, great; if not, we'll fix it in the next version.)

<img width="840" alt="image" src="https://user-images.githubusercontent.com/6355854/121683854-f1bea480-ca8b-11eb-9feb-f72726992df4.png">

**Comment by teixeirak** [comment]
@ValentineHerr , no urgency on this. I just modified manually for now.

**Comment by ValentineHerr** [comment]
this should be fixed
