### ISSUE TITLE
showing data

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/ForestGEO-tree-rings#137]
**From R2: "Data: I am not sure why there is no data shown on any of the figures presented. Inclusion of the raw data should help support the results of the analysis. Since they are omitted, it makes me (as a reader) question if they are intentionally not shown as a result of some discrepancy. At the very least, I would like to see data included in a panel of each figure, and a comment as to why it was omitted in the rest."**

The simple answer is that (1) there's inherently a lot of variation in tree-ring (or any tree growth) data, so showing the data makes it tough to visualize the trends; and (2) we're packing so much into all the figures that adding data would be too much.

My first inclination is maybe to add a figure showing data to the main manuscript or the SI. We want to keep this simple.

@ValentineHerr , I'd like to hear what you think about this.

**Comment by ValentineHerr** [comment]
I agree with both (1) and (2).

We could reproduce the same figures with the data points in SI and refer to them in the legend of the figures in the main manuscript if someone want to see the variability in the data... 
If we want to show it in the main manuscript, I could try to add a little inset plot with the points and the trend line... (e.g. in the top-left-hand corner of each panel but) I don't know if we would even see anything and if we did, it probably can only be done in figure 4 and maybe 6... 5 is too busy.

**Comment by teixeirak** [comment]
I think that trying to show the same figures with all the data would probably just make an absolute mess, right? 

Perhaps a better solution would be to make a figure of a full model for one species with data included? If you think that makes sense/ is relatively feasible, I'll pick a species or two to try.

**Comment by ValentineHerr** [comment]
> Perhaps a better solution would be to make a figure of a full model for one species with data included

Yes, we can try that.

**Comment by crollinson** [comment]
Agreed with doing a a full model figure for at least one species.  One things we've done in our QAQC during model building is this where I generate the full model posterior for example trees (random or stratified cherry-pick).  It's not great, but [here's an example](https://www.dropbox.com/s/wkdxoza7lz7odzp/gam6_sanitycheck2.pdf?dl=0) from early iterations of our paper.  I think if you do something on a stand or species level rather than individual trees, it'll look better and not hit the tree ring people annoyed you're not getting the variance perfectly.

FWIW, the other response I give when I've gotten comments like this to before it to use some language highlighting that your figures are showing _partial effects_ and so showing the raw data would be difficult because in multivariate analyses, any single factor is showing only one part of the variance and so it's hard to meaningfully show the "raw" data.

**Comment by teixeirak** [comment]
Thanks, @crollinson.

I like the individual plots, but think a species or stand level plot would be more appropriate here.

Good point about the partial effects. Perhaps it makes more sense to do a species- or stand-level plot of predicted vs fit?

**Comment by teixeirak** [comment]
Perhaps try RW model for PIPO at LT (pink in fig below)?  The effects of climate, DBH, and year are relatively well-balanced, and there's not an overwhelming amount of data, which might make it good for this purpose.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/6355854/127222909-89bc45df-b375-4e92-94cf-a82a3bc037f3.png">

**Comment by ValentineHerr** [comment]
Started working on this and this is where I am at:

![image](https://user-images.githubusercontent.com/19673377/127235926-7ba330eb-67c6-418d-a6cd-3ae0dac67698.png)


I think the trends match the data pretty well..
I'll add a couple other adjustment (like grey rectangles and having the trend on top).
Maybe a color per core? 

But before I move forward I want to make sure this is what you were thinking of, @teixeirak.

**Comment by teixeirak** [comment]
This is looking great! Actually, I'm thinking it would probably be better to use this in Fig. 1 (in place of the multi-species plot). What do you think?

A couple small changes: 

- you can drop the grey boxes and lines for the climate variables.
- perhaps put a log scale on the y-axis?

**Comment by ValentineHerr** [comment]
Good idea to put in in Fig. 1.

This is what it looks like now. If you like it I'll save it and and update figure 1.

![image](https://user-images.githubusercontent.com/19673377/127335021-d20eb3b6-1fac-4380-92c8-63da1b750020.png)

**Comment by teixeirak** [comment]
Thanks! That generally looks good, but unfortunatley the log scale doesn't help, so let's switch back to linear scale. Can you also please adjust the aspect ratio so that each box is approximately square (or much closer)? Also, we don't need the species label (but can just crop it out if it's easier that way).

**Comment by teixeirak** [comment]
Also, if it's very easy, it wouldn't hurt to generate plots like this for all site-species combinations.

**Comment by ValentineHerr** [comment]
I updated Figure 1 with this:
![image](https://user-images.githubusercontent.com/19673377/127352144-fe4292cc-d409-4fd5-a35c-932f0b39d569.png)

For all other site-species combinations... it would take more time... This was a bit of a "quick" way to get to that figure. it would need a bit more thoughts and coding to generate all other plots automatically. Not impossible though. Just let me know if you think it is worth it and for what cases we need them (this was for with_Year and log_core_measurements but there is all other combos of cases).

**Comment by teixeirak** [comment]
Looks awesome; thanks!

No worries about making this for all the species-- I was just thinking it would be good to do if you simply had to turn on a loop or such.

**Comment by teixeirak** [comment]
All set here. Many thanks, @ValentineHerr !
