### ISSUE TITLE
bug in plotting DBH trends at CB

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/ForestGEO-tree-rings#140]
@ValentineHerr , I've found another bug while working on the summary figure: 

For PIEN at CB, there are significant first- and 2nd-order effects of DBH in both models with and without year (identical, as year is not in best model):

<img width="739" alt="image" src="https://user-images.githubusercontent.com/6355854/127794206-79b99116-8c52-4ba1-96cd-ff645c46142c.png">

This gives this curve:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/6355854/127794323-6bbda4f0-b752-47f0-b34b-b75bf1154062.png">

This does not match what's plotted in either models with year (because it's a dashed line, indicating that 2nd order is non-sig)... (PIEN in yellow)

![image](https://user-images.githubusercontent.com/6355854/127794399-612f3422-f690-40ea-9941-a35957cb9387.png)

or the model without year:
![image](https://user-images.githubusercontent.com/6355854/127794411-4129c592-2040-49ff-93cb-e2ecff6d0768.png)

Same thing seems to be going on with ABBI (red in plots above). I'm not sure about other species.

**Comment by teixeirak** [comment]
Also, for PIEN, significant climate effects are plotted as non-sig.

**Comment by ValentineHerr** [comment]
Hmmm yes, I see the solid/dashed/towdashed lines have all been mixed up. I'll fix this now... sorry for that and thanks for catching it!

**Comment by ValentineHerr** [comment]
I pushed something but I don't think it is right yet (I think it messed those linetypes up even more).... will push new updates once everything has run again.

**Comment by ValentineHerr** [comment]
I think the figures are good to go now. Let me know if you see more issues.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr !
