### ISSUE TITLE
finish data availability statement

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/ForestGEO-tree-rings#146]
The data availability statement needs to be finalized. It currently reads:

## Data availability
Code and full results are available via the open-access project repository in GitHub (https://github.com/EcoClimLab/ForestGEO-tree-rings) and archived in Zenodo **(DOI: TBD)**. Original data from each site are available through various public databases, as indicated in the original publications, or upon reasonable request from the authors. Data for **[# TBD]** of the sites are archived in the The DendroEcological Network (DEN) database (SCBI, **[others TBD]**, Rayback et al., 2020) and/or the International Tree-Ring Data Bank, ITRDB (CB).

TO DO:
- [ ] update on DEN (@RHelcoski ; https://github.com/EcoClimLab/ForestGEO_dendro/issues/27) - we don't necessarily need to do any more work here, but we do need to update this statement
- [x] release this on Zenodo, provide DOI (@teixeirak )

**Comment by RHelcoski** [comment]
I think the ideal statement would be if we said exactly which sets are in DEN. We would potentially get 9 on DEN. [https://github.com/EcoClimLab/ForestGEO_dendro/blob/master/sites_data_publishing.csv](url) I just need help on HKK NE and ZOF. Then I will email DEN again and get an estimate of when they think they can have the data live so the final statement can be: (names of data sets) all available on DEN starting (date). Or something similar

**Comment by teixeirak** [comment]
It's not critical to get all the sites in DEN, so I wouldn't worry about getting more in at this point, unless they're already in process/ close to being ready. And then we can just change the wording to "Data for *[# TBD]* of the sites are archived, or soon-to-be archived, in The DendroEcological Network (DEN) database..."

**Comment by RHelcoski** [comment]
alright, that works. Most are in DEN's hands at the moment or just waiting on a response from a PI or two

**Comment by teixeirak** [comment]
updated link: https://github.com/EcoClimLab/ForestGEO_dendro/blob/master/sites_data_publishing.csv

**Comment by teixeirak** [comment]
@RHelcoski , please confirm that this data availability statement is (or will be, within a couple weeks and definitely by the time paper is published) accurate: 

Code and full results are available via the open-access project repository in GitHub (https://github.com/EcoClimLab/ForestGEO-tree-rings) and archived in Zenodo (DOI: 10.5281/zenodo.5484261). Original data from each site are available through various public databases, as indicated in the original publications, or upon reasonable request from the authors. **Data for seven of the sites (BCNM, SCBI, LDW, HF, NIO, LT, SC) have been submitted to The DendroEcological Network (DEN) database (Rayback et al., 2020).**

**Comment by teixeirak** [comment]
(This is the last piece needed to send the manuscript files back to the journal.)

**Comment by RHelcoski** [comment]
Is BCNM Barro Colorado Island? I have it down as BCI. I haven't submitted LT or NOI to DEN yet (just missing one doc from each). But I imagine by the time the publication is out all of the sets will be sent to DEN.

**Comment by teixeirak** [comment]
> Is BCNM Barro Colorado Island? I have it down as BCI. 

Yes, it's BCNM. Most of the cores were not actually taken on the island.

I agree it's safe to trust that we'll get the documents submitted by the time it's published.
